// Products
export const SHOW_PRODUCTS = "SHOW_PRODUCTS";
export const SET_LOADING = "SET_LOADING";

// Basket
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_ARTICLE_FROM_BASKET =
	"REMOVE_ARTICLE_FROM_BASKET";
export const REMOVE_ITEM_FROM_BASKET = "REMOVE_ITEM_FROM_BASKET";
