// Products
export const SHOW_PRODUCTS = "SHOW_PRODUCTS";
export const SET_LOADING = "SET_LOADING";

// Basket
export const ADD_ARTICLE_TO_BASKET = "ADD_ARTICLE_TO_BASKET";
export const ADD_ITEM_TO_BASKET = "ADD_ITEM_TO_BASKET";
export const REMOVE_ARTICLE_FROM_BASKET =
	"REMOVE_ARTICLE_FROM_BASKET";
export const REMOVE_ITEM_FROM_BASKET = "REMOVE_ITEM_FROM_BASKET";

// Auth
export const SET_USER = "SET_USER";
export const ADD_NEW_USER = "ADD_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
